export const EVENT_USER_JOIN = 'userJoin'
export const EVENT_CREATE_EVENT = 'createEvent'
export const CLIENT_EVENT_LIST_EVENTS = 'client_listEvents'
export const SERVER_EVENT_LIST_EVENTS = 'server_listEvents'
export const EVENT_SUBSCRIBE = 'subscribeEvent'
export const EVENT_PLAYER_JOIN = 'joinEvent'
export const EVENT_UPDATE_EVENT = 'updateEvent'
